# Generated by Django 2.2.7 on 2019-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
